%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.1 on {{2016,6,3},{12,44,27}}

-ifndef(riak_core_pb).
-define(riak_core_pb, true).

-define(riak_core_pb_gpb_version, "3.21.1").

-ifndef('RIAKOBJECT_PB_PB_H').
-define('RIAKOBJECT_PB_PB_H', true).
-record(riakobject_pb,
        {bucket,                        % = 1, bytes
         key,                           % = 2, bytes
         val                            % = 3, bytes
        }).
-endif.

-endif.
